### ISSUE TITLE
How to integrate git-lfs with our own git server.

### ISSUE THREAD

**Issue by akif-ih** [Caellian/node-git-lfs#3]
@Caellian I forked your project and try to contribute by implementing locking api. But i have a question may be you could help me. Let's suppose i have implemented my own git server, and want to integrate this extension with my server, how could i achieve this.

**Comment by Caellian** [comment]
This repository is highly developmental. I forked the previous project and tried adding locking API to it. It ended up working as it was a project I used to introduce myself to JS backend dev. I am also encumbered with several other projects I'm working on for university and OSS community so I have very limited free time. If you find a nice solution for LFS servers I'd appreciate you letting me know. I was recently closing old projects and decided I'll likely rewrite this one in Go some time soon but only for AWS S3.

As for your question, running `node server.js` should suffice, there's also a few scripts for different tasks defined in `package.json` - they can be ran using `yarn start` and so on. Configure it using either [environment variables](https://github.com/Caellian/node-git-lfs/blob/master/config/custom-environment-variables.yml) or [config files](https://github.com/Caellian/node-git-lfs/tree/master/config).

Again, I was working on this as a requirement for a group project I was part on but we never ended up using it as it mysteriously didn't seem to work. Maybe I configured it incorrectly, maybe I messed everything up so I recommend you use [hons82 branch](https://github.com/hons82/node-git-lfs).
